/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IUniV3likeQuoterCore } from "../IUniV3likeQuoterCore";

export class IUniV3likeQuoterCore__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniV3likeQuoterCore {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IUniV3likeQuoterCore;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "poolAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "zeroForOne",
        type: "bool",
      },
      {
        internalType: "int256",
        name: "amountSpecified",
        type: "int256",
      },
      {
        internalType: "uint160",
        name: "sqrtPriceLimitX96",
        type: "uint160",
      },
    ],
    name: "quote",
    outputs: [
      {
        internalType: "int256",
        name: "amount0",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "amount1",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
